// prc_rest,sm_on_rest
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrest event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_rest", OBJECT_SELF);
    ExecuteScript("sm_on_rest", OBJECT_SELF);
}
