// prc_onmodload,sm_on_mod_ld
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onmoduleload event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onmodload", OBJECT_SELF);
    ExecuteScript("sm_on_mod_ld", OBJECT_SELF);
}
