// prc_onheartbeat,x3_mod_def_hb
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onheartbeat event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onheartbeat", OBJECT_SELF);
    ExecuteScript("x3_mod_def_hb", OBJECT_SELF);
}
