// prc_onunaquire,sm_on_unacquire
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onunaquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onunaquire", OBJECT_SELF);
    ExecuteScript("sm_on_unacquire", OBJECT_SELF);
}
