// prc_onrespawn,sm_on_respawn
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrespawn event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onrespawn", OBJECT_SELF);
    ExecuteScript("sm_on_respawn", OBJECT_SELF);
}
