// prc_onplayerchat,dmfi_onplychat
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerchat event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onplayerchat", OBJECT_SELF);
    ExecuteScript("dmfi_onplychat", OBJECT_SELF);
}
