// prc_ondying,sm_on_dying
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdying event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_ondying", OBJECT_SELF);
    ExecuteScript("sm_on_dying", OBJECT_SELF);
}
