// prc_onleave,sm_on_client_lv
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onclientleave event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onleave", OBJECT_SELF);
    ExecuteScript("sm_on_client_lv", OBJECT_SELF);
}
