// prc_onactivate,sm_on_act
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onactivateitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onactivate", OBJECT_SELF);
    ExecuteScript("sm_on_act", OBJECT_SELF);
}
